// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sbywbwrhcrmtbbmsupbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieXdid3JoY3JtdGJibXN1cGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDcyNjAsImV4cCI6MjA2Mzg4MzI2MH0._428z80U5uC9YVw87MndKDlxwuEh3mIl0S74CtVdEPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);